# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doubling_packer <- function(x) {
    .Call('_spacker_doubling_packer', PACKAGE = 'spacker', x)
}

doubling_unpacker <- function(x, n) {
    .Call('_spacker_doubling_unpacker', PACKAGE = 'spacker', x, n)
}

multiplier_packer <- function(x) {
    .Call('_spacker_multiplier_packer', PACKAGE = 'spacker', x)
}

multiplier_unpacker <- function(x, n) {
    .Call('_spacker_multiplier_unpacker', PACKAGE = 'spacker', x, n)
}

encode_short <- function(x) {
    .Call('_spacker_encode_short', PACKAGE = 'spacker', x)
}

